In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import import_ipynb
import tensorflow as tf
from scipy import misc
import cv2
import numpy as np
import facenet
import detect_face
import os
import time
import pickle

importing Jupyter notebook from facenet.ipynb
importing Jupyter notebook from detect_face.ipynb


In [2]:
#input_video="akshay_mov.mp4"
modeldir = './model/20170511-185253.pb'
classifier_filename = './class/classifier.pkl'
npy='./npy'
train_img="./train_img"

In [5]:
# Using OpenCV to initialize the webcam
cap = cv2.VideoCapture(0)

with tf.Graph().as_default():
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.6)
    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options, log_device_placement=False))
    with sess.as_default():
        pnet, rnet, onet = detect_face.create_mtcnn(sess, npy)

        minsize = 20  # minimum size of face
        threshold = [0.6, 0.7, 0.7]  # three steps's threshold
        factor = 0.709  # scale factor
        margin = 44
        frame_interval = 3
        batch_size = 1000
        image_size = 182
        input_image_size = 160
        
        HumanNames = os.listdir(train_img)
        HumanNames.sort()

        print('Loading Modal')
        facenet.load_model(modeldir)
        images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
        embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
        phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")
        embedding_size = embeddings.get_shape()[1]


        classifier_filename_exp = os.path.expanduser(classifier_filename)
        with open(classifier_filename_exp, 'rb') as infile:
            (model, class_names) = pickle.load(infile)

        #video_capture = cv2.VideoCapture(input_video)
        c = 0


        print('Start Recognition')
        prevTime = 0
        while True:
            ret, frame = cap.read()

            #frame = cv2.resize(frame, (0,0), fx=0.8, fy=0.8)    #resize frame (optional)

            curTime = time.time()+1    # calc fps
            timeF = frame_interval

            if (c % timeF == 0):
                find_results = []

                if frame.ndim == 2:
                    frame = facenet.to_rgb(frame)
                frame = frame[:, :, 0:3]
                bounding_boxes, _ = detect_face.detect_face(frame, minsize, pnet, rnet, onet, threshold, factor)
                nrof_faces = bounding_boxes.shape[0]
                print('Detected_FaceNum: %d' % nrof_faces)

                if nrof_faces > 0:
                    det = bounding_boxes[:, 0:4]
                    img_size = np.asarray(frame.shape)[0:2]

                    cropped = []
                    scaled = []
                    scaled_reshape = []
                    bb = np.zeros((nrof_faces,4), dtype=np.int32)

                    for i in range(nrof_faces):
                        emb_array = np.zeros((1, embedding_size))

                        bb[i][0] = det[i][0]
                        bb[i][1] = det[i][1]
                        bb[i][2] = det[i][2]
                        bb[i][3] = det[i][3]

                        # inner exception
                        if bb[i][0] <= 0 or bb[i][1] <= 0 or bb[i][2] >= len(frame[0]) or bb[i][3] >= len(frame):
                            print('Face is very close!')
                            continue

                        cropped.append(frame[bb[i][1]:bb[i][3], bb[i][0]:bb[i][2], :])
                        cropped[i] = facenet.flip(cropped[i], False)
                        scaled.append(misc.imresize(cropped[i], (image_size, image_size), interp='bilinear'))
                        scaled[i] = cv2.resize(scaled[i], (input_image_size,input_image_size),
                                               interpolation=cv2.INTER_CUBIC)
                        scaled[i] = facenet.prewhiten(scaled[i])
                        scaled_reshape.append(scaled[i].reshape(-1,input_image_size,input_image_size,3))
                        feed_dict = {images_placeholder: scaled_reshape[i], phase_train_placeholder: False}
                        emb_array[0, :] = sess.run(embeddings, feed_dict=feed_dict)
                        predictions = model.predict_proba(emb_array)
                        print(predictions)
                        best_class_indices = np.argmax(predictions, axis=1)
                        best_class_probabilities = predictions[np.arange(len(best_class_indices)), best_class_indices]
                        # print("predictions")
                        print(best_class_indices,' with accuracy ',best_class_probabilities)

                        # print(best_class_probabilities)
                        if best_class_probabilities>0.53:
                            cv2.rectangle(frame, (bb[i][0], bb[i][1]), (bb[i][2], bb[i][3]), (0, 255, 0), 2)    #boxing face

                            #plot result idx under box
                            text_x = bb[i][0]
                            text_y = bb[i][3] + 20
                            print('Result Indices: ', best_class_indices[0])
                            print(HumanNames)
                            for H_i in HumanNames:
                                if HumanNames[best_class_indices[0]] == H_i:
                                    result_names = HumanNames[best_class_indices[0]]
                                    result_accuracy = str(best_class_probabilities[0])
                                    result = result_names + result_accuracy
                                    cv2.putText(frame, result, (text_x, text_y), cv2.FONT_HERSHEY_COMPLEX_SMALL,
                                                .5, (0, 0, 255), thickness=1, lineType=1)
                else:
                    print('Alignment Failure')
            # c+=1
            cv2.imshow('Video', frame)

            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        cap.release()
        cv2.destroyAllWindows()

Loading Modal
Model filename: ./model/20170511-185253.pb
Start Recognition
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 0
Alignment Failure
Detected_FaceNum: 1


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


[[0.01619775 0.12405306 0.51406875 0.15191573 0.13645793 0.05730677]]
[2]  with accuracy  [0.51406875]
Detected_FaceNum: 1
[[0.03939087 0.05538691 0.22744627 0.21966828 0.35023902 0.10786865]]
[4]  with accuracy  [0.35023902]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.0341723  0.11212036 0.43195618 0.08721623 0.20754492 0.12699002]]
[2]  with accuracy  [0.43195618]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.02949541 0.17516498 0.45096368 0.07599728 0.12102143 0.14735722]]
[2]  with accuracy  [0.45096368]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.02790869 0.04574466 0.79187906 0.02903296 0.05997516 0.04545947]]
[2]  with accuracy  [0.79187906]
Result Indices:  2
['Akshay Kumar', 'Nawazuddin Siddiqui', 'Salman Khan', 'Shahrukh Khan', 'Sunil Shetty', 'Sunny Deol']


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.02564499 0.14877686 0.47121448 0.04916312 0.11806722 0.18713333]]
[2]  with accuracy  [0.47121448]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00628941 0.13202818 0.28804774 0.06484678 0.23831581 0.27047209]]
[2]  with accuracy  [0.28804774]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.0075263  0.17952516 0.32558694 0.0403744  0.29315052 0.15383668]]
[2]  with accuracy  [0.32558694]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01158671 0.1654128  0.35557748 0.09541001 0.13051329 0.24149971]]
[2]  with accuracy  [0.35557748]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00508559 0.06642594 0.69458067 0.05946957 0.11377562 0.06066262]]
[2]  with accuracy  [0.69458067]
Result Indices:  2
['Akshay Kumar', 'Nawazuddin Siddiqui', 'Salman Khan', 'Shahrukh Khan', 'Sunil Shetty', 'Sunny Deol']


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01314448 0.19539163 0.42631905 0.08526495 0.10376865 0.17611124]]
[2]  with accuracy  [0.42631905]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00730904 0.26367158 0.32551172 0.07932316 0.08825405 0.23593044]]
[2]  with accuracy  [0.32551172]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.0068855  0.12694253 0.40253956 0.07070636 0.1680813  0.22484476]]
[2]  with accuracy  [0.40253956]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01728342 0.09483438 0.1938926  0.07148664 0.18125283 0.44125013]]
[5]  with accuracy  [0.44125013]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 2
[[0.00813436 0.05523326 0.3150288  0.15317295 0.11562613 0.3528045 ]]
[5]  with accuracy  [0.3528045]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


[[0.11859811 0.13769543 0.02416899 0.36756993 0.15142527 0.20054227]]
[3]  with accuracy  [0.36756993]
Detected_FaceNum: 1
[[0.00557304 0.06564317 0.20875383 0.15359798 0.1004151  0.46601689]]
[5]  with accuracy  [0.46601689]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00540965 0.24019066 0.25332581 0.17253875 0.19801055 0.13052458]]
[2]  with accuracy  [0.25332581]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00325127 0.37173511 0.35488098 0.12002198 0.0733685  0.07674216]]
[1]  with accuracy  [0.37173511]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01169273 0.20888551 0.35753492 0.09840491 0.22325529 0.10022664]]
[2]  with accuracy  [0.35753492]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00751596 0.09247397 0.69880406 0.08868172 0.05516937 0.05735492]]
[2]  with accuracy  [0.69880406]
Result Indices:  2
['Akshay Kumar', 'Nawazuddin Siddiqui', 'Salman Khan', 'Shahrukh Khan', 'Sunil Shetty', 'Sunny Deol']


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00885766 0.11696146 0.53989122 0.0715175  0.09891404 0.16385812]]
[2]  with accuracy  [0.53989122]
Result Indices:  2
['Akshay Kumar', 'Nawazuddin Siddiqui', 'Salman Khan', 'Shahrukh Khan', 'Sunil Shetty', 'Sunny Deol']


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00711542 0.27659703 0.39830145 0.13031028 0.11340524 0.07427058]]
[2]  with accuracy  [0.39830145]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01154994 0.09161979 0.45869974 0.07954791 0.25495712 0.1036255 ]]
[2]  with accuracy  [0.45869974]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01059048 0.13377694 0.31320199 0.07733912 0.37245231 0.09263916]]
[4]  with accuracy  [0.37245231]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.0091959  0.09831502 0.49083262 0.13945087 0.16101495 0.10119064]]
[2]  with accuracy  [0.49083262]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00624748 0.24414262 0.32136642 0.08285223 0.14555291 0.19983834]]
[2]  with accuracy  [0.32136642]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.01997614 0.12115748 0.5222232  0.13955227 0.10806477 0.08902614]]
[2]  with accuracy  [0.5222232]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00424742 0.16856381 0.36054297 0.10847268 0.21039156 0.14778157]]
[2]  with accuracy  [0.36054297]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.


Detected_FaceNum: 1
[[0.00520823 0.06330628 0.44186062 0.05235446 0.30526389 0.13200651]]
[2]  with accuracy  [0.44186062]


/home/yasir/.local/lib/python3.6/site-packages/ipykernel_launcher.py:82: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
